### ISSUE TITLE
Encryption insecure

### ISSUE THREAD

**Issue by ddmler** [ericmann/sessionz#1]
Your implementation for EncryptionHandler is not secure. I would recommend using something like paragonie/halite instead.

**Comment by ericmann** [comment]
I have plans to use something stronger. Literally copy-pasted from an example on php.net for the initial build out.

**Comment by enygma** [comment]
@ddmler while a dependency like that is nice, it's not flexible enough for most users as there are usually constraints on what they can install on the server (requires PECL libsodium after all). I'd suggest more of a "secure by default" approach that allows the use of different "handler" types based on user input with libsodium being the _default_. That provides a good base to work from but also provides the user with options that can better fit with their needs.

Making an absolute security change would, obviously, be ideal but not entirely realistic.
